### ISSUE TITLE
Unit test or bats for testing Drupal settings

### ISSUE THREAD

**Issue by simesy** [govCMS/scaffold-tooling#15]
I have added a basic test that checks to scaffold-tooling can be built into a drupal site with composer, and that the settings values can be accessed with drush.

https://github.com/govCMS/scaffold-tooling/pull/14/commits/f41f1426d0399b832cee413cab9e6b0531acfc69#diff-1d37e48f9ceff6d8030570cd36286a61R26-R27

I am looking for someone to suggest a way to check settings values thoroughly, and perhaps some framework around testing the ./scripts as well.

**Comment by AlexSkrypnyk** [comment]
To clarify these requirements a bit more: we need to test settings and scripts like black box: only environment variables should change on the input to get some output

**Comment by AlexSkrypnyk** [comment]
Ok, the solution is to use bats-core and https://github.com/jasonkarns/bats-mock:
bats-core will run tests, while bats-mock help us to mock the binaries that scripts call (drush etc).
I will try to put some basic testing around this in a PR shortly.

**Comment by simesy** [comment]
Do we just execute the PHP scripts (ie the *.settings.php) directly with bats?

**Comment by simesy** [comment]
Yes, "unit testing", as much possible.

**Comment by AlexSkrypnyk** [comment]
This has been implemented. Closing.
