### ISSUE TITLE
CLAMAV_MODE can never be set to 0

### ISSUE THREAD

**Issue by AlexSkrypnyk** [govCMS/scaffold-tooling#188]
In `settings.php`:
```
$clam_mode = getenv('CLAMAV_MODE') ?: 1;
```

If `CLAMAV_MODE` has a value of `0` (`MODE_DAEMON`) - the `$clam_mode` will always be `1`.

**Comment by steveworley** [comment]
This has been updated and is obsolete as we do not support ClamAV at the moment. We will look to remove this in future.
