### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by AlexSkrypnyk** [govCMS/scaffold-tooling#3]
@tobybellwood @simesy 
I would like to help to setup CI using CircleCI for this project.

As a minimum, the CI would contain the following:
- `composer.json` validation
- PHP code linting for php files using PHPCS
- Bash code linting for php files using shellcheck

Once setup, other checks can be added later.

If this is something that you are interested, please setup CI build in CircleCI for this project (no config is required) and I will submit a PR with CI configuration. This is required to allow my fork to run CI in PR.

**Comment by simesy** [comment]
Would the CI configuration for circle sit side by side? Like, there would be .gitlab-ci-main.yml and .circle-ci-main.yml (or whatever)?

**Comment by simesy** [comment]
or a circle folder next to gitlab, more like it.

**Comment by AlexSkrypnyk** [comment]
This is the CI for this package itself, not the consumer sites.

**Comment by simesy** [comment]
Yep, I mean in this repository.
