### ISSUE TITLE
Incorrect temporary path

### ISSUE THREAD

**Issue by sonnykt** [govCMS/scaffold-tooling#45]
The scaffold incorrectly sets the temporary path for Drupal in
https://github.com/govCMS/scaffold-tooling/blob/develop/drupal/settings/all.settings.php#L37
```php
$settings['file_temporary_path'] = 'sites/default/files/private/tmp';
```
According to [D8.8 changelog](https://www.drupal.org/node/3039255), the correct settings is `file_temp_path`, so the above line must be:
```php
$settings['file_temp_path'] = 'sites/default/files/private/tmp';
```

Without setting the correct path, the temporary path fallbacks to `/tmp` it causes issues with exporting webform submissions.

**Comment by AlexSkrypnyk** [comment]
Merged

**Comment by AlexSkrypnyk** [comment]
Thank you @sonnykt
