### ISSUE TITLE
Evaluate use of dev packages in `require`

### ISSUE THREAD

**Issue by larowlan** [govCMS/scaffold-tooling#59]
Are packages like drupal/console, phar-io/manifest, phar-io/version, webflo/drupal-finder and webmozart/path-util needed in the production auto-loader?

Could they be moved to require-dev?

**Comment by simesy** [comment]
I assume they can be moved to require-dev.

If a history is important though, they first were included in this commit https://github.com/govCMS/govcms8lagoon/commit/1c41efba89dbe41533ecdb8f2695fca48cf6c7ac

**Comment by simesy** [comment]
@fubarhouse since I can't see back past your commit above, are there any reasons you can think of why the packages above need to be in `require` and not `require-dev`?

**Comment by stooit** [comment]
These have been moved to `require-dev` in the `9.x` branch - closing this
